#!/bin/bash

# prompt user for input file directory to watch
echo "input file directory:"
read INPUT_FILE_DIRECTORY

#run hadd
echo "running watch-progress..."

TIME=$(date)
echo "-- start: $TIME"

NUMBER_OF_PROCESSED_FILES=0
NUMBER_OF_TOTAL_FILES=1163
PERCENT_COMPLETE=0.0

FILE_NUMBER_DIFFERENCE=0
let FILE_NUMBER_DIFFERENCE=$NUMBER_OF_TOTAL_FILES-$NUMBER_OF_PROCESSED_FILES

while [ $FILE_NUMBER_DIFFERENCE -ne 0 ]

do

    NUMBER_OF_PROCESSED_FILES=$(ls $INPUT_FILE_DIRECTORY | wc -l)
    let FILE_NUMBER_DIFFERENCE=$NUMBER_OF_TOTAL_FILES-$NUMBER_OF_PROCESSED_FILES
    let PERCENT_COMPLETE=100*$NUMBER_OF_PROCESSED_FILES/$NUMBER_OF_TOTAL_FILES
    echo "progress : $NUMBER_OF_PROCESSED_FILES / $NUMBER_OF_TOTAL_FILES [$PERCENT_COMPLETE %]"
    sleep 10

done

END_TIME=$(date)
echo "-- end: $END_TIME"



